include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - lib/gen/**
  errors:
    invalid_annotation_target: ignore
linter:
  rules:
